package.json
src/containers/InstalledApps/index.jsx
src/scss/main.scss
yarn.lock

import bootstrap

---

package.json
src/components/Base/Button/index.jsx
src/components/Base/Button/index.scss
src/containers/InstalledApps/index.jsx
src/containers/InstalledApps/index.scss
yarn.lock

Manage apps

---

.eslintignore
.eslintrc.js
.gitattributes
.gitignore
README.md
config/webpack.dev.js
package.json
server/middleware/render.js
server/server.js
server/views/index.pug
src/App.jsx
src/components/Base/Button/index.scss
src/components/Base/Input/index.scss
src/components/Base/Select/index.scss
src/components/ManageTabs/index.scss
src/containers/InstalledApps/index.scss
src/scss/main.scss
yarn.lock

modify manage-apps css

---

.eslintignore
.npmrc
config/webpack.prod.js
core/logger.js
package.json
server/middleware/render.js
yarn.lock

1. update eslint-babel to latest, fix eslint mobx `@action` error
> see: https://github.com/eslint/eslint/issues/9767
2. disable package-lock

upgrade eslint-babel, fix eslint mobx @action throw error

---

.babelrc
package.json
server/mock/cluster-nodes.json
server/mock/clusters.json
server/routes.js
server/routes/apps.js
src/components/Base/Checkbox/checkbox.jsx
src/components/Base/Checkbox/group.jsx
src/components/Base/Checkbox/index.js
src/components/Base/Checkbox/index.scss
src/components/Base/Pagination/index.js
src/components/Base/Pagination/index.scss
src/components/Base/Select/index.scss
src/components/Base/Table/index.js
src/components/Base/Table/index.scss
src/components/Base/Table/table.jsx
src/components/Status/index.jsx
src/components/Status/index.scss
src/containers/ClusterDetail/index.jsx
src/containers/ClusterDetail/index.scss
src/containers/Clusters/index.jsx
src/containers/Clusters/index.scss
src/containers/InstalledApps/index.jsx
src/containers/InstalledApps/index.scss
src/scss/variables.scss
src/stores/AppStore.js
src/utils/index.js
yarn.lock

add Table/Pagination/Checkbox/Status component
add ManageClusters & ManageClustersDetail page

add manage-clusters & manage-clusters-detail page

---

package.json
server/middleware/render.js
server/views/index.pug
src/App.jsx
src/routes/wrapper.js
src/stores/AppStore.js
src/stores/RootStore.js

- container component will call ``onEnter`` when client router changes
- add ``window.__SSR__`` to avoid fetching data twice when refreshing the browser

fix client data fetching

---

jest.config.json
package.json
src/containers/ClusterDetail/index.jsx
src/containers/Clusters/index.jsx
tests/components/Base/Checkbox.test.js
tests/components/Base/Pagination.test.js
tests/components/Base/Table.test.js
yarn.lock

use mobx.toJS to serialize ObservableArray
add the Table/Pagination/Checkbox component's test case

Component test

---

package.json
server/middleware/auth.js
server/middleware/check-client-webpack.js
server/middleware/render.js
server/middleware/store.js
server/routes.js
server/server.js
webpack.dev.js

change server side code as cjs format, reduce babel transform
fix precommit hook

deprecate babel-node, use babel-register

---

server/middleware/check-client-webpack.js
server/middleware/render.js
server/models/roles.json
server/models/users.json
server/routes.js
server/server.js
server/views/index.pug
src/containers/AppDeploy/index.jsx
src/containers/AppDetail/index.jsx
src/containers/ClusterDetail/index.jsx
src/containers/Clusters/index.jsx
src/containers/Home/index.jsx
src/containers/InstalledApps/index.jsx
src/hoc/preload.js
src/routes/wrapper.js
src/stores/AppStore.js
src/stores/ClusterStore.js
tests/pages/Home.test.js

1.fix server side routes
2. remove _SSR label in views
3. fix mobx stores

feat: add preload decorator to handle server and client side render

---

lib/request.js
lib/utils.js
server/local_config.yml.example
server/middleware/render.js
server/middleware/store.js
server/server.js
src/components/AppList/index.jsx
src/containers/Home/index.jsx
src/hoc/preload.js
src/scss/variables.scss
src/stores/AppStore.js
src/stores/ClusterStore.js
src/stores/RootStore.js
src/stores/Store.js

1. lib/request can accept serverUrl from local_config
2. update stores
3. fix Home component

upgrade: store and request lib

---

server/middleware/auth.js
server/middleware/session.js
src/App.jsx
src/routes/index.js

- fix auth middleware, ctx.session.isNew
- src/routes, auth /manage pages in react-router

fix: server side auth middleware, authenticate /manage pages in react-router

---

.travis.yml
README.md
jest.config.json
package.json
yarn.lock

- travis-ci add yarn cache
- update readme
- jest.config.json add coverage 
- update package.json scripts

Add codecov tool

---

lib/utils.js
package.json
yarn.lock

`local_config.yml` deep merge `config.yml`
fix: #64

[ci skip] fix: local_config.yml deep merge

---

lib/request.js
src/containers/Manage/Categories/index.jsx
src/containers/Manage/Repos/Add/index.jsx
src/containers/Manage/Runtimes/Add/index.jsx
src/stores/RootStore.js
src/stores/Store.js

- fix category page server render

fix: store prototype add notification msg handler

---

server/routes/login.js
server/server.js
src/pages/Login/index.jsx
src/stores/LoginStore.js
webpack.prod.js

- fix login route api msg handle
- koa-static add max-age http header to use browser caching

fix: css module tag missing in production build

---

src/components/Layout/Admin/index.jsx
src/components/Loading/index.jsx
src/components/Loading/index.scss
src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Apps/Deploy/index.scss
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Categories/index.jsx
src/pages/Admin/Clusters/index.jsx
src/pages/Admin/Repos/index.jsx
src/pages/Admin/Runtimes/index.jsx

1. add app deploy static page
2. add page loading style

app deploy static page and loading component

---

src/components/Layout/Admin/index.jsx
src/components/Layout/Admin/index.scss
src/components/TagShow/index.jsx
src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Clusters/index.jsx
src/pages/Admin/Repos/index.jsx
src/pages/Admin/Runtimes/Detail/index.jsx
src/pages/Admin/Runtimes/index.jsx
src/stores/app/deploy.js
src/stores/app/index.js
src/stores/cluster/index.js
src/stores/repo/index.js
src/stores/runtime/index.js

upgrade: page delete、search、refresh、pagination methods

 upgrade: page delete、search、refresh、pagination methods

---

src/components/Base/Modal/index.scss
src/components/Base/Radio/group.jsx
src/components/Base/Radio/radio.jsx
src/components/Base/Select/index.scss
src/components/DetailCard/AppCard.jsx
src/components/Layout/Admin/Dialog/index.scss
src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Overview/AppList/index.jsx
src/pages/Admin/Overview/AppList/index.scss
src/pages/Admin/Overview/ClusterList/index.jsx
src/pages/Admin/Overview/ClusterList/index.scss
src/pages/Admin/Overview/RepoList/index.scss
src/pages/Admin/Overview/index.jsx
src/pages/Admin/Repos/Add/index.jsx
src/pages/Admin/Runtimes/Add/index.jsx
src/stores/app/deploy.js
src/stores/app/version.js

- fix: add  Radio conmponent value type
- upgrade: overview page style and modify create version
- fixed runtime、repo edit page refresh data loss

fix: add  Radio conmponent value type

---

src/components/Base/Table/index.scss
src/components/Card/CardTitle/index.scss
src/components/TdName/index.scss
src/components/UserInfo/TotalCard/index.scss
src/pages/Admin/Apps/Detail/columns.js
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Categories/Detail/index.jsx
src/pages/Admin/Clusters/Detail/index.jsx
src/pages/Admin/Clusters/index.jsx
src/pages/Admin/Overview/AppList/index.jsx
src/pages/Admin/Overview/AppList/index.scss
src/pages/Admin/Overview/ClusterList/index.jsx
src/pages/Admin/Overview/ClusterList/index.scss
src/pages/Admin/Overview/RepoList/index.jsx
src/pages/Admin/Overview/RepoList/index.scss
src/pages/Admin/Repos/Add/index.jsx
src/pages/Admin/Repos/Detail/index.jsx
src/pages/Admin/Repos/RepoList.jsx
src/pages/Admin/Repos/index.jsx
src/pages/Admin/Runtimes/Add/index.jsx
src/pages/Admin/Runtimes/Detail/index.jsx
src/pages/Admin/Runtimes/index.jsx
src/scss/variables.scss
src/stores/Store.js
src/stores/app/deploy.js
src/stores/app/index.js
src/stores/cluster/index.js
src/stores/repo/index.js
src/stores/runtime/create.js
src/stores/runtime/index.js

page table query add status

---

src/pages/Admin/Repos/Detail/index.jsx
src/stores/repo/index.js

- fix: repo detail page tags error

fix: repo detail page tags error

---

src/pages/Admin/Clusters/Detail/index.jsx
src/pages/Admin/Overview/AppList/index.jsx
src/pages/Admin/Overview/AppList/index.scss
src/pages/Admin/Overview/ClusterList/index.jsx
src/pages/Admin/Overview/ClusterList/index.scss
src/pages/Admin/Overview/Panel/index.jsx
src/pages/Admin/Overview/Panel/index.scss
src/pages/Admin/Overview/RepoList/index.jsx
src/pages/Admin/Overview/RepoList/index.scss
src/pages/Admin/Overview/index.jsx
src/pages/Admin/Overview/index.scss
src/pages/Admin/Repos/Add/index.jsx
src/pages/Admin/Runtimes/Add/index.jsx
src/stores/repo/create.js

update: repo page Provider Radio modify Checkbox

update: normal user overview page

---

locales/en/translation.json
locales/zh/translation.json
src/components/AppList/index.jsx
src/components/Banner/index.jsx
src/components/Card/CardTitle/index.jsx
src/components/Footer/index.jsx
src/components/Footer/index.scss
src/components/Header/index.jsx
src/components/Header/index.scss
src/components/Layout/Admin/BackBtn.jsx
src/components/Nav/index.jsx
src/components/TabsNav/index.jsx
src/components/UserInfo/TotalCard/index.jsx
src/components/UserInfo/index.jsx
src/hoc/trans.js
src/pages/Admin/Overview/AppList/index.jsx
src/pages/Admin/Overview/ClusterList/index.jsx
src/pages/Admin/Overview/Panel/index.jsx
src/pages/Admin/Overview/RepoList/index.jsx
src/pages/Admin/Overview/index.jsx
src/pages/AppDetail/index.jsx
src/pages/Login/index.jsx
src/stores/LoginStore.js
src/utils/index.js
tests/__snapshots__/App.test.js.snap
tests/pages/__snapshots__/Home.test.js.snap
tests/setup.js

- fix login store
- move change locale btns to footer

Add trans hoc, complement i18n placeholder

---

src/pages/Admin/Runtimes/Add/index.jsx
src/pages/Admin/Runtimes/Add/index.scss
src/pages/AppDetail/index.jsx
src/stores/runtime/create.js

 upgrade runtime add page, add get zones method

---

config/i18n-config.js
package.json
src/components/DetailCard/RuntimeCard.jsx
src/components/TimeAxis/index.jsx
src/components/TimeShow/index.jsx
src/pages/Admin/Clusters/index.jsx
src/pages/Admin/Repos/Detail/index.jsx
src/pages/Admin/Runtimes/index.jsx
src/pages/Admin/Users/index.jsx
src/pages/AppDetail/index.jsx
src/pages/ClusterDetail/index.jsx
src/pages/Clusters/index.jsx
src/utils/index.js
yarn.lock

update: using dayjs to format datetime

---

src/components/Base/Modal/index.scss
src/components/TagNav/index.scss
src/components/TdName/index.jsx
src/components/TdName/index.scss
src/pages/Admin/Apps/Deploy/Cell/index.scss
src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Apps/Deploy/index.scss
src/pages/Admin/Categories/index.jsx
src/pages/Admin/Categories/index.scss
src/pages/Admin/Clusters/Detail/index.jsx
src/pages/Admin/Clusters/index.jsx
src/pages/Admin/Overview/AppList/index.jsx
src/pages/Admin/Overview/Panel/index.scss
src/pages/Admin/Runtimes/Detail/index.jsx
src/pages/AppDetail/index.jsx
src/pages/AppDetail/index.scss
src/stores/RootStore.js
src/stores/runtime/index.js

cluster、runtime detail page add delete operation

---

src/components/Base/Radio/index.scss
src/components/Base/Select/index.scss
src/components/Base/Select/option.jsx
src/components/Base/Select/select.jsx
src/components/Base/Table/index.scss
src/components/DetailCard/index.scss
src/locales/zh/translation.json
src/pages/Admin/Apps/Deploy/Cell/index.scss
src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Apps/Deploy/index.scss
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Categories/index.scss
src/pages/Admin/Clusters/index.jsx
src/pages/Admin/Repos/Detail/index.jsx
src/stores/repo/index.js

- upgrade operate style, fix app deploy page radio style bug

fix repo detail page runtime refresh query bug

---

src/components/Base/Modal/index.scss
src/components/Rectangle/index.scss
src/components/TdName/index.scss
src/components/TimeShow/index.jsx
src/components/TimeShow/index.scss
src/components/TodoList/index.jsx
src/locales/zh/translation.json
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Apps/Detail/tabs/cluster-columns.js
src/pages/Admin/Apps/Detail/tabs/version-columns.js
src/pages/Admin/Clusters/Detail/index.jsx
src/pages/Admin/Repos/Add/index.jsx
src/pages/Admin/Runtimes/Add/index.jsx
src/pages/AppDetail/Body/QingCloud/index.jsx
src/pages/AppDetail/Information/index.jsx
src/pages/AppDetail/Information/index.scss

app detail add translate, Add、Remove、Validate button add translate

app detail table column add translate

---

src/components/Base/Modal/index.scss
src/components/Base/Table/index.scss
src/components/Card/index.scss
src/components/DetailCard/AppCard.jsx
src/components/DetailCard/index.scss
src/components/Rectangle/AppImages/index.scss
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Categories/Detail/index.jsx
src/pages/Admin/Categories/index.jsx
src/pages/Admin/Clusters/Detail/index.jsx
src/pages/Admin/Clusters/index.jsx
src/pages/Admin/Overview/index.jsx
src/pages/Admin/Repos/Detail/index.jsx
src/pages/Admin/Repos/index.jsx
src/pages/Admin/Runtimes/Detail/index.jsx
src/pages/Admin/Runtimes/index.jsx
src/pages/AppDetail/Meta/index.scss
src/scss/index.scss
src/stores/app/index.js
src/stores/app/version.js
src/stores/cluster/index.js
src/stores/repo/index.js
src/stores/runtime/index.js

- fix serch and filter method reset currentPage

Fix search word and status state not reset correctly

---

src/pages/AppDetail/index.jsx
src/pages/AppDetail/index.scss
src/utils/string.js

Fix version list card scrollbar

fix(app detail): Version list sort order

---

.travis.yml
Makefile
deploy-docker.sh

refactor: Using deploy script in travis.yml to push docker image

---

.travis.yml
deploy-docker.sh

Reverts openpitrix/dashboard#271

Revert "[ci skip] fix: travis deploy add skip_cleanup"

---

README.md
deploy-docker.sh
docs/quick-start.md

Fix quick-start.md format
Update readme

refactor: deploy-docker.sh only push latest image

---

.travis.yml
deploy-docker.sh

refactor: Caching docker layer when build in travis

---

src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Repos/Detail/index.jsx
src/stores/repo/index.js

Fix deploy page get repo selector

fix: Repo detail query runtime label by repo selector

---

package.json
server/middleware/auth.js
server/middleware/gzip.js
server/routes/page.js
webpack.prod.js
yarn.lock

Add gzip middleware to server
Upgrade webpack, webpack-cli to v4.17

feat: Gzip webpack bundle

---

server/middleware/auth.js
server/routes/login.js
src/pages/Login/index.jsx
src/routes/renderRoute.js
src/utils/index.js

feat: Login support redirect_url

---

package.json
server/server.js
src/utils/sock-client.js
yarn.lock

* Fix `Mixed Content` in https
* Add helmet to koa

fix: Connect websocket in https using wss

---

Makefile

refactor: Makefile support tagging docker image

---

src/components/Base/Table/noData.jsx
src/components/DetailCard/UserCard.jsx
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Categories/Detail/index.jsx
src/pages/Admin/Overview/index.jsx
src/pages/Admin/Repos/Detail/index.jsx
src/pages/Admin/Repos/index.jsx
src/pages/Admin/Runtimes/Detail/index.jsx
src/pages/Admin/Runtimes/index.jsx
src/pages/Admin/Users/Detail/index.jsx
src/pages/Admin/Users/Detail/index.scss
src/pages/Admin/Users/index.jsx
src/pages/Admin/index.js
src/routes/index.js
src/stores/Store.js
src/stores/UserStore.js
src/stores/app/index.js
src/stores/app/version.js
src/stores/cluster/index.js
src/stores/repo/create.js
src/stores/repo/index.js
src/stores/runtime/index.js
src/utils/columns/app-columns.js
src/utils/columns/cluster-columns.js
src/utils/columns/repo-columns.js
src/utils/columns/runtime-columns.js

* Modify table relative query methods

Add user detail page

---

src/pages/Admin/Apps/Deploy/index.jsx
src/stores/app/deploy.js

fix: Deploy app click submit button throw error when config file is empty

---

src/components/Status/index.jsx
src/components/Status/index.scss
src/pages/Admin/Clusters/index.jsx
src/stores/cluster/index.js

Update cluster list, order by create_time

refactor: Add more transition status

---

src/components/Base/Table/table.jsx
src/components/Loading/index.scss
src/components/Menu/index.jsx
src/components/Menu/index.scss
src/pages/Admin/Apps/NewDetail/index.jsx
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Clusters/index.jsx
src/pages/Home/index.jsx
src/pages/Store/index.jsx
src/stores/app/index.js

* fix: Optimizate table loading style
* solve #356

feat: Developer menu add apps data for api

---

src/components/Base/Icon/index.jsx
src/components/Base/Icon/index.scss
src/components/Menu/index.jsx
src/pages/Admin/Categories/index.jsx

fix: Side nav icon color

---

src/components/Base/Table/table.jsx

fix: Table filter condition can not be clear when data source is empty

---

src/components/Base/Modal/index.scss
src/components/DetailCard/UserCard.jsx
src/components/Menu/index.jsx
src/components/Menu/index.scss
src/locales/en/translation.json
src/locales/zh/translation.json
src/pages/Admin/Apps/Add/index.jsx
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Users/Detail/index.jsx
src/pages/Admin/Users/GroupCard/index.jsx
src/pages/Admin/Users/GroupCard/index.scss
src/pages/Admin/Users/index.jsx
src/pages/Home/index.jsx
src/pages/Profile/index.jsx
src/pages/Purchased/index.jsx
src/pages/Store/index.jsx
src/stores/UserStore.js
src/utils/static-data.js

* fix: App query and delete according to status

feat: User pages integrate API

---

lib/request.js
lib/utils.js
server/config.yml
server/middleware/render.js
server/middleware/store.js
server/routes/api.js
server/routes/login.js
server/server.js
src/stores/LoginStore.js
src/stores/Store.js
test/components/Base/__snapshots__/Table.test.js.snap

Refactor http request agent
Refactor server side api route, base store request proxy
Config.yml add clientId, clientSecret, accessToken keys

feat: Api request add auth token

---

src/index.js
src/utils/index.js
src/utils/sock-client.js

Fix utils getCookie
Remove console.log in sock-client

fix: Websocket auth failed

---

config/i18n.config.js
src/locales/zh/translation.json
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Categories/Detail/index.jsx

Rename App index `Modify category` text
Fix category detail mappingStatus not imported err

fix: I18n default lang zh not work in safari

---

src/components/Banner/index.scss
src/components/DetailCard/ClusterCard.jsx
src/components/DetailCard/index.scss
src/components/Menu/index.jsx
src/components/Menu/index.scss
src/components/TagNav/index.jsx
src/locales/en/translation.json
src/locales/zh/translation.json
src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Clusters/index.jsx
src/pages/Admin/Overview/Panel/index.jsx
src/pages/Admin/Overview/RepoList/index.jsx
src/pages/Admin/Overview/RepoList/index.scss
src/pages/Admin/Overview/index.jsx
src/pages/Purchased/index.jsx
src/stores/cluster/index.js

* feat: Purchased table add app and actions

fix: Overview normal user show runtime list

---

src/components/Base/Tooltip/index.scss
src/components/Menu/index.jsx
src/components/Menu/index.scss
src/locales/en/translation.json
src/locales/zh/translation.json
src/pages/Admin/Apps/Detail/DetailBlock/index.jsx
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Overview/index.jsx
src/pages/Admin/Users/index.jsx
src/pages/Runtimes/index.jsx
src/pages/Runtimes/index.scss
src/stores/app/index.js

fix: Resolve developer menu app show bug

---

src/components/Base/Select/select.jsx
src/components/Status/index.scss
src/locales/en/translation.json
src/locales/zh/translation.json
src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Apps/Detail/index.scss
src/pages/Admin/Apps/Review/index.jsx
src/pages/AppDetail/index.jsx
src/pages/AppDetail/index.scss
src/stores/app/deploy.js
src/stores/app/index.js
src/stores/app/version.js
src/stores/cluster/index.js
src/stores/repo/index.js
src/stores/runtime/index.js

* feat: Add rejected reason show
* fix: Deploy app query runtime and skip url bug

 feat: Review apps add status filter

---

src/components/DetailCard/RuntimeCard.jsx
src/components/DetailCard/index.scss
src/routes/renderRoute.js

fix: Cluster detail card hide long namespace text

---

src/components/DetailCard/RuntimeCard.jsx
src/pages/Admin/Apps/Review/index.jsx
src/stores/app/deploy.js

* fix: RuntimeCard span tag error

fix: Deploy app version filter bug

---

src/components/DetailCard/RuntimeCard.jsx
src/pages/Admin/Apps/Review/index.jsx
src/pages/Store/index.jsx
src/stores/UserStore.js
src/stores/app/deploy.js

* fix: Store page load app data error

fix: Password modify error

---

src/components/Layout/Grid/section.jsx
src/routes/renderRoute.js
src/scss/_mixins.scss
src/scss/partial/_grid.scss
test/App.test.js

refactor: Section gap change with current login user

---

server/middleware/auth.js
server/routes/api.js
server/routes/login.js
src/components/AppList/index.jsx
src/components/Layout/index.jsx
src/pages/Admin/Apps/Add/index.jsx
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Clusters/Detail/index.jsx
src/pages/Admin/Overview/AppList/index.jsx
src/pages/Admin/Overview/ClusterList/index.jsx
src/pages/Admin/Overview/index.jsx
src/pages/AppDetail/index.jsx
src/pages/AppDetail/index.scss
src/pages/Home/index.jsx
src/pages/Profile/index.jsx
src/pages/Purchased/index.jsx
src/pages/Store/index.jsx
src/routes/index.js
src/stores/UserStore.js
src/stores/app/index.js
src/stores/app/version.js
src/stores/repo/index.js

*  fix: Overview skip url and version delete logic
* solve #451

Add token when not login

---

src/components/Footer/index.jsx
src/locales/en/translation.json
src/locales/zh/translation.json
src/pages/Admin/Apps/Add/index.jsx
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Overview/index.jsx

* fix: Document link error
* fix: Developer menu lasest app error

fix: App create file check bug

---

src/components/Footer/index.jsx
src/pages/Admin/Apps/Add/index.jsx
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Purchased/index.jsx
src/pages/Store/index.jsx
src/routes/renderRoute.js
src/stores/app/index.js
src/stores/app/version.js

fix: Create app error

---

src/components/Footer/index.jsx
src/locales/zh/translation.json
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Apps/Review/index.jsx
src/pages/Admin/Overview/RepoList/index.jsx
src/pages/AppDetail/index.jsx
src/stores/app/index.js
src/utils/index.js

* fix: App Detail page remove delete button

fix: Overview app query remove status filter

---

src/components/Base/Table/table.jsx
src/components/Header/index.jsx
src/components/Layout/SideNav/index.jsx
src/components/Layout/index.jsx
src/components/TdName/index.scss
src/locales/en/translation.json
src/locales/zh/translation.json
src/pages/Admin/Apps/Detail/DetailBlock/index.jsx
src/pages/Admin/Clusters/Detail/VMbase/index.jsx
src/pages/Admin/Clusters/Detail/index.jsx
src/pages/Admin/Clusters/Detail/index.scss
src/pages/Admin/Overview/index.jsx
src/pages/AppDetail/index.jsx
src/pages/AppDetail/index.scss
src/pages/Home/index.jsx
src/pages/Purchased/index.jsx
src/pages/Runtimes/index.scss
src/pages/SSHKeys/columns.js
src/pages/SSHKeys/index.jsx
src/pages/SSHKeys/index.scss
src/providers/user.js
src/stores/cluster/detail.js
src/stores/key_pair/index.js

* fix: Home detail header show bug
* fix: Purchased page apps query bug

feat: Add cluster attach or detach key pairs

---

lib/request.js
server/logger.js
server/middleware/store.js
server/routes/api.js
server/routes/auth-token.js
server/routes/login.js
server/server.js
server/session-config.js
server/utils.js
src/pages/AppDetail/index.jsx
src/pages/Home/index.jsx
src/pages/Login/index.jsx
src/pages/Store/index.jsx
src/providers/user.js
src/routes/index.js
src/routes/wrapper.js
src/stores/Store.js
src/stores/app/index.js
src/stores/app/version.js
src/stores/cluster/detail.js
src/stores/repo/index.js
src/stores/user/index.js
src/utils/index.js
test/pages/Home.test.js

Fix Home page search trigger two times componentDidMount
Refactor server routes
See: #467 #475

refactor: Auth login using different token, add expired check

---

src/components/Base/CodeMirror/index.jsx
src/components/DetailCard/UserCard.jsx
src/components/Layout/SideNav/navMap.js
src/components/TimeShow/index.jsx
src/config/roles.js
src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Apps/Deploy/index.scss
src/pages/Admin/Clusters/Detail/index.jsx
src/pages/Admin/Users/GroupCard/index.jsx
src/pages/Admin/Users/index.jsx
src/pages/Admin/Users/index.scss
src/pages/AppDetail/Body/Helm/index.scss
src/scss/index.scss

Deploy app editor add line number, filename
See: #436

fix: User list and detail page, style bugs

---

src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/index.scss
src/locales/zh/translation.json
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Repos/RepoList/index.scss

fix: Developer related style issues

---

server/routes/api.js
src/components/Header/index.jsx
src/components/Header/index.scss
src/locales/zh/translation.json
src/pages/Admin/Runtimes/Detail/index.jsx
src/pages/AppDetail/index.jsx
src/pages/Runtimes/index.jsx
src/stores/app/deploy.js
src/stores/app/index.js

* feat: Header operate menus add icon

fix: Deploy page token auth error

---

lib/request.js
server/routes/auth-token.js
src/locales/zh/translation.json
src/pages/Admin/Apps/Add/index.jsx

Fix lib/request, add backend detail error check
Fix auth login route

refactor: Create app can only select s3 type repo

---

src/components/Base/Table/index.scss
src/components/DetailCard/UserCard.jsx
src/components/DetailCard/index.scss
src/components/TagShow/index.jsx
src/components/TagShow/index.scss
src/components/TimeShow/index.jsx
src/components/TimeShow/index.scss
src/locales/en/translation.json
src/locales/zh/translation.json
src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Apps/Deploy/index.scss
src/pages/Admin/Apps/Detail/index.jsx
src/pages/Admin/Apps/index.jsx
src/pages/Admin/Clusters/index.jsx
src/pages/Admin/Overview/index.jsx
src/pages/Admin/Runtimes/index.jsx
src/pages/Admin/Users/Detail/index.jsx
src/pages/Admin/Users/GroupCard/index.jsx
src/pages/Admin/Users/index.jsx
src/pages/AppDetail/Body/QingCloud/index.scss
src/stores/Store.js
src/stores/app/deploy.js
src/stores/app/index.js
src/stores/user/index.js

fix: Admin overview repo list show bug

fix: Deploy app query no runtimes add note

---

src/components/Layout/index.jsx
src/pages/Admin/Apps/Deploy/index.jsx
src/pages/Admin/Clusters/Detail/index.jsx
src/pages/AppDetail/index.jsx

* fix: Deploy page button translate

fix: Detail page init loading value

---

src/pages/SSHKeys/index.jsx
src/stores/cluster/detail.js
src/stores/key_pair/index.js

fix: SSHKey page nodes query error

---

package.json
src/App.jsx
src/components/Deploy/index.scss
src/components/Loading/index.scss
src/pages/Dashboard/Apps/index.jsx

Fix src/App LazyLoad tail close tag
Refactor dashboard apps change viewType

fix: Package.json script compat with npm, remove yarn cmd

---

src/components/Base/Image/index.jsx
src/components/Base/Table/index.scss
src/components/Card/index.jsx
src/components/Layout/TitleBanner.jsx
src/pages/AppDetail/Meta/index.jsx
src/pages/Dashboard/Apps/Deploy/index.jsx
src/pages/Dashboard/Apps/Detail/DetailBlock/index.jsx
src/pages/Dashboard/Apps/index.jsx
src/pages/Dashboard/Clusters/index.jsx
src/pages/Dashboard/Repos/Detail/tabs/runtime-columns.js
src/pages/Dashboard/Runtimes/index.jsx
src/pages/Dashboard/Users/index.jsx
src/pages/Purchased/index.jsx
src/utils/columns/runtime-columns.js

* Fix table actions column style

Image letter change error

---

src/components/Base/Image/index.jsx
src/pages/Dashboard/Runtimes/Add/index.jsx
src/pages/Dashboard/Runtimes/providers.js

refactor: Create runtime add aliyun provider

---

src/locales/zh/translation.json
src/pages/Dashboard/Clusters/Detail/Helm/index.jsx
src/pages/Dashboard/Clusters/Detail/index.scss

feat: add additional_info for helm page

---

package.json
src/App.jsx
src/components/LazyLoad/index.jsx
src/components/Loading/index.jsx
src/pages/Dashboard/Clusters/Detail/Helm/index.jsx
src/pages/Dashboard/Clusters/Detail/VMbase/index.jsx
src/pages/Dashboard/Clusters/Detail/index.jsx
src/stores/cluster/detail.js
webpack.dev.js
yarn.lock

Webpack dev build add notifier
Add LazyLoad component

fix: Cluster detail loading when runtime type not resolved

---

.eslintrc.js
lib/utils.js
server/server.js
src/index.js

fix: Watch server config files not reload

---

server/config.yml
src/pages/Dashboard/Apps/Detail/index.jsx
src/stores/RootStore.js

fix: App detail broken doc link

---

src/components/Base/Button/index.scss
src/components/Base/Pagination/index.scss
src/components/Base/Table/index.scss
src/components/Base/Table/table.jsx
src/components/Base/Tooltip/index.scss
src/components/DetailCard/ClusterCard.jsx
src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/index.scss
src/components/Layout/SideNav/navMap.js
src/components/Layout/index.jsx
src/components/Layout/index.scss
src/components/Loading/index.scss
src/components/Toolbar/index.jsx
src/components/Toolbar/index.scss
src/locales/zh/apps.json
src/locales/zh/translation.json
src/pages/Dashboard/Clusters/Detail/Helm/index.jsx
src/pages/Dashboard/Clusters/Detail/index.jsx
src/pages/Dashboard/Clusters/Detail/index.scss
src/pages/Dashboard/Clusters/index.jsx
src/routes/index.js
src/scss/index.scss
src/scss/partial/_color.scss
src/scss/partial/_grid.scss

Refactor table component style for new design
Resolve #583

feat: Developer test and user instance pages

---

src/components/ErrorBoundary/index.jsx
src/components/ErrorBoundary/index.scss
src/routes/wrapper.js

refactor: Add error boundary check to root component

---

src/components/Base/Image/index.jsx
src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/navMap.js
src/locales/zh/apps.json
src/pages/Dashboard/Apps/Info/index.jsx
src/pages/Dashboard/Apps/Info/index.scss
src/pages/Dashboard/index.js
src/routes/index.js
src/scss/_mixins.scss
src/stores/app/index.js
src/stores/testing_env/create.js

feat: App information mgmt and service contract

---

package.json
src/components/Base/Table/table.jsx
src/components/Layout/Card/index.scss
src/components/Loading/index.scss
src/pages/Dashboard/Clusters/index.jsx
src/stores/cluster/detail.js
yarn.lock

Remove json2yaml package, dupe with js-yaml

fix: Cluster detail yaml string transform

---

src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/navMap.js
src/components/Layout/index.jsx
src/locales/zh/translation.json
src/pages/Dashboard/Apps/index.jsx
src/pages/Login/index.jsx
src/providers/user.js
src/utils/icons.js

feat: Add new ISV navigation

---

server/middleware/auth.js
server/routes/api.js
server/routes/login.js
server/utils.js
src/App.jsx
src/pages/Login/index.jsx
src/providers/user.js
src/routes/renderRoute.js
src/stores/Store.js
src/utils/index.js

fix: Auth token not updated cause page redirect to login

---

src/components/Base/Button/index.scss
src/components/Base/Popover/index.scss
src/locales/zh/apps.json
src/pages/Dashboard/Apps/Info/index.jsx
src/pages/Dashboard/Categories/index.scss
src/pages/Dashboard/Versions/Detail/index.jsx
src/pages/Dashboard/Versions/Detail/index.scss
src/pages/Dashboard/Versions/VersionEdit/index.jsx
src/pages/Dashboard/Versions/VersionEdit/index.scss
src/providers/user.js
src/stores/app/index.js
src/stores/app/version.js

solve #523 -- Version submit review and info check

feat: Review submitted app version and validate info

---

src/components/Base/Image/index.jsx
src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/index.scss
src/components/Layout/SideNav/navMap.js
src/components/Layout/index.scss
src/components/Status/index.jsx
src/components/Status/index.scss
src/components/TimeShow/index.scss
src/locales/zh/translation.json
src/pages/Dashboard/Apps/Audits/index.jsx
src/pages/Dashboard/Apps/Audits/index.scss
src/pages/Dashboard/Apps/Info/index.jsx
src/pages/Dashboard/Apps/Info/index.scss
src/pages/Dashboard/Clusters/index.jsx
src/pages/Dashboard/Reviews/Detail/index.jsx
src/pages/Dashboard/Reviews/Detail/index.scss
src/pages/Dashboard/Reviews/index.jsx
src/pages/Dashboard/Reviews/index.scss
src/pages/Dashboard/Versions/Detail/index.jsx
src/pages/Dashboard/Versions/index.jsx
src/providers/user.js
src/routes/index.js
src/scss/index.scss
src/stores/app/index.js
src/stores/app/version.js
src/stores/cluster/index.js
src/utils/index.js

Solve #590 -- integrated review API

feat: Integrate app version review api for all roles

---

server/routes/page.js
src/components/Base/Select/index.scss
src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/index.scss
src/locales/zh/apps.json
src/pages/Dashboard/Apps/Audits/index.jsx
src/pages/Dashboard/Apps/Card/index.jsx
src/pages/Dashboard/Apps/Card/index.scss
src/pages/Dashboard/Apps/Info/index.jsx
src/pages/Dashboard/Apps/MyApps/Empty/index.jsx
src/pages/Dashboard/Apps/MyApps/index.jsx
src/pages/Dashboard/Apps/MyApps/index.scss
src/pages/Dashboard/Versions/index.jsx
src/pages/Login/index.jsx
src/stores/app/index.js

* fix: Modify my apps page style
solve #577

refactor: Side nav display recent visited apps

---

src/components/Base/Modal/index.scss
src/pages/Dashboard/Users/index.jsx
src/pages/Dashboard/Users/index.scss

fix: Create user modal style

---

bin/locale.js
package.json

Add watch mode to bin/locale.js

refactor: Watch locale files

---

src/components/Base/Modal/index.jsx
src/components/Base/Modal/index.scss
src/components/Layout/Dialog/index.jsx
src/locales/zh/user.json
src/pages/Account/SSHKeys/index.jsx
src/pages/Account/SSHKeys/index.scss
src/pages/Dashboard/Apps/index.jsx
src/pages/Dashboard/Apps/index.scss
src/pages/Dashboard/Clusters/Detail/VMbase/index.jsx
src/pages/Dashboard/Clusters/Detail/index.jsx
src/pages/Dashboard/Users/index.jsx
src/pages/Dashboard/Users/index.scss
src/stores/user/index.js

Remove dead codes of all pages

refactor: Modal and Dialog, unify style

---

src/components/Layout/BreadCrumb/index.jsx
src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/navMap.js
src/components/Layout/index.jsx
src/components/MenuLayer/index.jsx
src/pages/Dashboard/Clusters/index.jsx
src/pages/Dashboard/Overview/ClusterList/index.jsx
src/pages/Dashboard/Providers/Applications/Detail/index.jsx
src/pages/Dashboard/Versions/Detail/index.jsx
src/portals/user/pages/PurchasedApps/Detail/index.jsx
src/routes/names.js
src/routes/portals/dev.jsx
src/routes/portals/isv.jsx
src/stores/app/deploy.js
src/stores/app/index.js
src/stores/app/version.js
src/stores/cluster/detail.js
src/stores/cluster/index.js
src/stores/runtime/credential.js
src/stores/runtime/index.js

* fix: Store action name judge
* fix: Solve code eslint errors

fix: SideNav routes

---

src/components/Header/index.jsx
src/config/form-check.js
src/locales/en/base.json
src/locales/zh/app-version.json
src/locales/zh/apps.json
src/locales/zh/base.json
src/locales/zh/provider.json
src/pages/AppDetail/index.scss
src/pages/Dashboard/Apps/Info/index.jsx
src/pages/Dashboard/Apps/Info/index.scss
src/pages/Dashboard/Providers/Create/index.jsx
src/pages/Dashboard/Providers/Create/index.scss
src/pages/Dashboard/Versions/VersionEdit/index.jsx
src/pages/Dashboard/Versions/VersionEdit/index.scss
src/stores/app/index.js
src/stores/app/version.js
src/stores/vendor/index.js

refactor: Add form field validation

---

Makefile
package.json
server/logger.js
server/middleware/auth.js
server/middleware/gzip.js
server/routes/api.js
server/server.js

Fix make run script
Replace some debug stmt to logger.info

refactor: Delegate winston log to docker logs

---

src/pages/Dashboard/Runtimes/Create/index.jsx
src/pages/Dashboard/Runtimes/Create/index.scss

When zones length more than five, show select

refactor: Runtime create page select zones style

---

src/components/Base/Table/index.scss
src/components/DetailTabs/index.scss
src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/index.scss
src/components/Layout/SideNav/navMap.js
src/components/MenuLayer/index.scss
src/components/Status/index.jsx
src/components/Status/index.scss
src/components/TdName/index.jsx
src/components/TdName/index.scss
src/locales/zh/provider.json
src/pages/Dashboard/Apps/Add/index.jsx
src/pages/Dashboard/Apps/Add/index.scss
src/pages/Dashboard/Providers/Create/index.jsx
src/pages/Dashboard/Versions/Detail/index.jsx
src/pages/Dashboard/Versions/Detail/index.scss
src/pages/Dashboard/Versions/index.jsx
src/portals/user/pages/PurchasedApps/index.jsx
src/stores/RootStore.js
src/stores/app/deploy.js
src/stores/vendor/index.js

* refactor: Version detail add query test instances
* fix: ISV apply limit

fix: Hide nav and meuns disabled data

---

src/components/Header/index.jsx
src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/index.scss
src/components/Layout/SideNav/navMap.js
src/pages/Dashboard/Clusters/Detail/VMbase/index.jsx
src/pages/Dashboard/Clusters/Detail/index.jsx
src/pages/Dashboard/Clusters/index.jsx
src/stores/cluster/detail.js
src/stores/cluster/index.js
src/stores/runtime/index.js

fix: Sandbox and user instances query for dev

---

src/components/Layout/SideNav/navMap.js
src/components/Layout/Stepper/index.jsx
src/components/NoteLink/index.jsx
src/components/NoteLink/index.scss
src/locales/en/base.json
src/locales/zh/apps.json
src/pages/Dashboard/Apps/Deploy/index.jsx
src/pages/Dashboard/Apps/Info/index.jsx
src/pages/Dashboard/Apps/Info/index.scss
src/pages/Dashboard/Providers/Applications/Detail/index.jsx
src/pages/Dashboard/Runtimes/index.jsx
src/pages/Dashboard/Runtimes/index.scss

* fix: Adjust runtimes page style

fix: Deploy add note link when no runtimes

---

src/pages/Dashboard/Clusters/Detail/index.jsx
src/stores/cluster/detail.js
src/stores/cluster/index.js

Display env params as yaml for helm

refactor(cluster detail): Display env params as json for vmbased

---

src/locales/zh/user.json

fix: Admin delete role tips

---

src/components/Base/Select/index.scss
src/components/Base/Select/select.jsx
src/components/Card/CardTitle/index.scss
src/components/Footer/index.scss
src/components/Layout/Card/index.scss
src/components/Layout/Stepper/index.scss
src/components/Layout/index.scss
src/components/TypeVersions/index.jsx
src/components/TypeVersions/index.scss
src/locales/en/base.json
src/locales/zh/apps.json
src/locales/zh/base.json
src/pages/AppDetail/index.jsx
src/pages/AppDetail/index.scss
src/pages/Dashboard/Apps/Deploy/index.jsx
src/pages/Dashboard/Apps/Deploy/index.scss
src/pages/Dashboard/Reviews/Detail/index.scss
src/pages/Home/index.jsx
src/pages/Home/index.scss
src/portals/user/Layout/index.scss
src/scss/partial/_grid.scss
test/pages/__snapshots__/Home.test.js.snap

* fix: Deploy instance change type bug

fix: User layout and deploy page style

---

package.json
server/config.yml
server/proxy-server.js
server/server.js
src/components/Layout/index.jsx
src/index.js
src/pages/Dashboard/Clusters/Detail/index.jsx
src/pages/Dashboard/Clusters/index.jsx
src/providers/sock-client.js
src/stores/RootStore.js
yarn.lock

[x] Add socket proxy server
[x] Refactor socket client event emitter with mitt

feat: Add websocket proxy server, refine socket client 

---

.gitignore
package.json
src/bin/locale.js
webpack.base.js
webpack.dev.js
webpack.prod.js
yarn.lock

Upgrade webpack to v4.29
Remove react-router-config
Move bin folder to src
Remove logs folder

refactor: Webpack config, reduce dupe config

---

src/components/NotFound/index.jsx
src/components/NotFound/index.scss
src/locales/zh/base.json
src/pages/Dashboard/Apps/Audits/index.jsx
src/pages/Dashboard/Apps/Audits/index.scss
src/pages/Dashboard/Apps/Info/index.jsx
src/pages/Dashboard/Versions/Detail/index.jsx
src/pages/Dashboard/Versions/index.jsx
src/pages/Dashboard/Versions/index.scss
src/stores/app/version.js

* fix: Not found page content
* fix: Version submit review when other version in-review

fix: Versions and audits pages style

---

server/routes/api.js
src/stores/app/deploy.js
src/stores/app/index.js

refactor: Api query limit by resource

---

.gitignore
.npmrc
package-lock.json
package.json

Fix react-popper version to v0.10

fix: Npm install not compat with yarn

---

.npmrc
src/scss/partial/_icon.scss

Fix node path mixed when using yarn dev

fix: Scss color define error

---

src/components/Base/Button/index.scss
src/components/Base/Input/index.scss
src/components/Base/Input/search.jsx
src/components/Base/Modal/index.scss
src/components/Base/Select/index.scss
src/components/Base/Table/index.scss
src/components/Base/Table/noData.jsx
src/components/Base/Tooltip/index.scss
src/components/Card/index.scss
src/components/DetailTabs/index.scss
src/components/Footer/index.scss
src/components/MenuLayer/index.jsx
src/components/MenuLayer/index.scss
src/components/TabsNav/index.scss
src/components/Toolbar/index.scss
src/pages/Dashboard/Account/SSHKeys/index.jsx
src/pages/Dashboard/Account/SSHKeys/index.scss
src/pages/Dashboard/Account/index.jsx
src/pages/Dashboard/Account/index.scss
src/pages/Dashboard/Runtimes/Create/index.scss
src/pages/Dashboard/Runtimes/index.scss
src/scss/_mixins.scss
src/scss/index.scss
test/components/Base/__snapshots__/Table.test.js.snap
test/pages/__snapshots__/Home.test.js.snap

主要修复终端用户界面上的样式问题，其他问题列在 #828 中 了

fix: User portal style issues

---

server/routes/api.js
src/components/MenuLayer/index.jsx
src/components/MenuLayer/index.scss
src/pages/Dashboard/Versions/Detail/index.jsx

* fix: App detail active version query error

fix: Nav menu role icon style

---

.npmrc
.travis.yml
Dockerfile

Fix slim-env image based on node:8-alpine

fix: Travis build failed due to slim image

---

src/components/Base/Icon/index.jsx
src/components/Base/Icon/index.scss
src/components/Base/Switch/index.jsx
src/config/runtimes.js
src/locales/zh/settting.json
src/pages/Dashboard/CloudEnv/index.jsx
src/pages/Dashboard/CloudEnv/index.scss
src/pages/Dashboard/NotificationServer/index.jsx
src/pages/Dashboard/NotificationServer/index.scss
src/stores/cloud_env/index.js
src/stores/notification_server/index.js
test/components/Base/__snapshots__/Table.test.js.snap
test/pages/__snapshots__/Home.test.js.snap

refine: Email service config api

---

src/portals/admin/pages/Users/ModalActions/index.jsx
src/portals/isv/pages/Users/Modals/index.jsx

fix: User description

---

server/routes/api.js
src/components/Base/Table/index.scss
src/components/TableTypes/index.scss
src/components/TypeVersions/index.scss

* fix: Query apps use token error

fix: Button group and table no data styles

---

src/locales/zh/base.json
src/pages/Dashboard/Runtimes/Create/index.jsx
src/pages/Dashboard/Runtimes/Credential/index.jsx
src/pages/Dashboard/Runtimes/Runtime/index.jsx
src/stores/testing_env/index.js

fix: Runtime platform name issues

---

src/components/Base/Input/input.jsx
src/components/Layout/SideNav/navMap.js
test/components/Base/__snapshots__/Table.test.js.snap
test/pages/__snapshots__/Home.test.js.snap

Fix input component add default value
fix #860

fix: Admin nav label

---

src/App.jsx
src/components/Layout/SideNav/navMap.js
src/pages/Dashboard/Account/index.jsx
src/routes/names.js
src/routes/portals/admin.jsx
src/routes/portals/dev.jsx
src/routes/portals/isv.jsx
src/routes/portals/user.jsx

refactor: Account url

---

package.json
server/config.yml
server/proxy-server.js
test/components/Base/__snapshots__/Table.test.js.snap
test/pages/__snapshots__/Home.test.js.snap

Fix proxy server empty socket url throw error

fix: Npm script add cross-env prefix

---

src/components/Base/Table/index.scss
src/components/Base/index.js
src/components/DetailTabs/index.scss
src/components/Layout/index.jsx
src/components/Layout/index.scss
src/components/TypeVersions/index.scss
src/pages/Dashboard/Apps/index.jsx
src/pages/Dashboard/Providers/Applications/Detail/index.jsx
src/pages/Dashboard/Providers/Applications/index.jsx
src/pages/Dashboard/Providers/Applications/index.scss
src/pages/Dashboard/Providers/CertificateInfo/index.jsx
src/pages/Dashboard/Providers/Detail/index.jsx
src/pages/Dashboard/Reviews/Detail/index.scss
src/stores/app/index.js
src/stores/vendor/index.js

* fix: Provider detail and deploy page style
* fix: All table query app status

fix: Providers table add query approvers

---

src/portals/isv/pages/Users/Modals/index.jsx
src/stores/user/group.js
src/stores/user/index.js

fix: ISV create user

---

src/pages/Dashboard/Clusters/index.jsx
src/stores/cluster/index.js

fix: Cluster search

---

src/pages/Dashboard/Runtimes/Runtime/index.jsx
src/pages/Dashboard/Runtimes/index.scss
src/stores/testing_env/create.js

fix: Runtime set initial credential name

---

src/config/runtimes.js
src/locales/zh/runtime.json
src/pages/Dashboard/Runtimes/Create/index.jsx
src/pages/Dashboard/Runtimes/Create/index.scss
src/stores/testing_env/create.js
src/stores/user/index.js

fix: Add namespace tip

---

src/components/Base/Table/index.scss
src/components/DetailTabs/index.scss
src/components/EnhanceTable/columns.js
src/pages/Dashboard/Account/SSHKeys/index.jsx
src/pages/Dashboard/Account/SSHKeys/index.scss
src/pages/Dashboard/Account/index.jsx
src/pages/Dashboard/Apps/Detail/index.jsx
src/pages/Dashboard/Apps/Detail/index.scss
src/pages/Dashboard/Apps/index.jsx
src/pages/Dashboard/Clusters/index.jsx
src/pages/Dashboard/Reviews/Detail/index.jsx
src/pages/Dashboard/Reviews/Detail/index.scss
src/pages/Dashboard/Reviews/index.jsx
src/pages/Dashboard/Runtimes/InstanceList/index.scss
src/portals/user/pages/PurchasedApps/index.jsx
src/portals/user/pages/PurchasedApps/index.scss
src/stores/app/index.js
src/stores/cluster/index.js
src/stores/user/index.js
test/components/Base/__snapshots__/Table.test.js.snap
test/pages/__snapshots__/Home.test.js.snap

* fix: Account and SSH page style
* fix: Add deploy total query in all app table
* fix: Use system auth query users by userId

fix: Review detail page and table sytle

---

src/components/Base/Table/index.scss
src/components/EnhanceTable/columns.js
src/components/TdUser/index.jsx
src/components/TdUser/index.scss
src/locales/zh/app-version.json
src/pages/Dashboard/Apps/Detail/index.jsx
src/pages/Dashboard/Apps/index.jsx
src/pages/Dashboard/Clusters/Detail/Helm/index.jsx
src/stores/app/index.js
src/stores/app/version.js

* fix: App active versions query in user view
* fix: Cluster detail page react error

fix: All app table show isr or user info

---

src/locales/zh/app-version.json
src/pages/AppDetail/index.jsx
src/pages/Dashboard/Apps/Detail/index.jsx

* fix: App detail page add provider info  query

fix: Version suspend operate id error

---

src/components/AppName/index.jsx
src/pages/Dashboard/Apps/Detail/index.jsx
src/pages/Dashboard/Apps/index.jsx
src/pages/Dashboard/Reviews/index.jsx
src/pages/Dashboard/Reviews/index.scss
src/portals/user/pages/PurchasedApps/Detail/index.jsx
src/stores/app/index.js
src/stores/app/version.js
src/stores/cluster/detail.js

* fix: Cluster detail query add with_detail param

fix: Review table add isv or submitter info

---

src/locales/zh/apps.json

fix: app_versions i18n

---

src/config/runtimes.js
src/pages/Dashboard/Clusters/index.jsx
src/pages/Dashboard/Overview/index.jsx
src/pages/Dashboard/Runtimes/Card/index.jsx
test/components/Base/__snapshots__/Table.test.js.snap
test/pages/__snapshots__/Home.test.js.snap

fix: k8s agent count

---

src/components/Base/Table/index.scss
src/components/EnhanceTable/columns.js
src/components/Status/index.scss
src/locales/zh/apps.json
src/locales/zh/base.json
src/pages/Dashboard/Apps/Detail/index.jsx
src/pages/Dashboard/Apps/Detail/index.scss
src/pages/Dashboard/Apps/index.jsx
src/pages/Dashboard/Clusters/index.jsx
src/pages/Dashboard/Providers/Applications/Detail/index.jsx
src/pages/Dashboard/Providers/Applications/index.jsx
src/pages/Dashboard/Reviews/Detail/index.jsx
src/pages/Dashboard/Reviews/Detail/index.scss
src/pages/Dashboard/Reviews/index.jsx
src/portals/user/pages/PurchasedApps/Detail/index.jsx
src/portals/user/pages/PurchasedApps/Detail/index.scss
src/portals/user/pages/PurchasedApps/index.jsx
src/stores/app/index.js
src/stores/app/version.js

* fix: Review detail page style

fix: Add ISV query in app detail

---

server/config.yml
server/proxy-server.js
server/server.js
src/pages/Dashboard/Clusters/Detail/index.jsx
src/pages/Dashboard/Clusters/index.jsx

refactor: Socket proxy server

---

server/config.yml
server/middleware/store.js
server/proxy-server.js
server/server.js
src/index.js
src/providers/sock-client.js

refactor: Proxy server

---

src/components/Layout/Card/index.scss
src/pages/Dashboard/Apps/Deploy/index.jsx
src/pages/Dashboard/Apps/Detail/index.jsx
src/pages/Dashboard/Reviews/index.jsx
src/pages/Dashboard/Reviews/index.scss
src/scss/partial/_color.scss
src/stores/cluster/index.js

* fix: Clusters data add user query

fix: Detail page table hove style

---

src/pages/AppDetail/index.jsx
src/pages/Dashboard/Apps/MyApps/index.jsx
src/pages/Dashboard/Categories/index.jsx
src/pages/Dashboard/Reviews/index.jsx
src/stores/app/version.js
test/components/Base/__snapshots__/Table.test.js.snap
test/pages/__snapshots__/Home.test.js.snap

* fix: Categories page add deploy total and isv info
* fix: Developer my apps query remove owner param

fix: Reviews table add operator info

---

server/routes/api.js
src/components/DetailTabs/index.jsx
src/pages/Dashboard/Runtimes/Card/index.jsx
src/stores/runtime/cluster.js
src/stores/testing_env/index.js

refactor: Runtime page instance count

---

src/locales/zh/cluster.json
src/routes/portals/isv.jsx

chore: Add cluster detail page for ISV role

---

src/components/TypeVersions/index.scss

style: App detail btn group

---

src/components/Base/Input/input.jsx
src/components/Base/Table/index.scss
src/locales/en/base.json
src/locales/zh/apps.json
src/pages/Dashboard/Apps/Info/index.jsx
src/portals/user/pages/Clusters/Detail/index.jsx
src/portals/user/pages/Clusters/index.jsx
src/portals/user/pages/PurchasedApps/Detail/index.jsx
src/portals/user/pages/PurchasedApps/index.jsx
src/portals/user/pages/Runtimes/index.jsx

fix: Uncontrolled component input if has default value

chore: Add translation for user pages

---

src/stores/app/version.js

fix: fetchVersion status

---

src/config/version.js
src/pages/Dashboard/Apps/Deploy/index.jsx
src/pages/Dashboard/Apps/Detail/index.jsx
src/pages/Dashboard/Versions/Detail/index.jsx
src/portals/user/pages/PurchasedApps/index.jsx
src/stores/app/version.js

* fix: App suspend operate filter version by status
*  fix: Deploy runtimes and purchased clusters add ower param

fix: Can delete suspended app version

---

public/logo_icon.svg
src/components/DetailCard/index.scss
src/components/Layout/SideNav/NavItem.jsx
src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/index.scss
src/components/Toolbar/index.scss
src/locales/zh/base.json

fix: Modify nav style

---

config/i18n.config.js

fix: i18n keySeparator

---

src/components/TdName/index.jsx
src/components/TdName/index.scss
src/pages/Dashboard/Clusters/Detail/Helm/columns.js

fix: TdName style

---

src/config/cloud-env.js
src/locales/zh/settting.json
src/pages/Dashboard/CloudInfo/index.jsx
src/pages/Dashboard/NotificationServer/index.jsx
src/stores/notification_server/index.js

chore: Test email server

---

src/components/DetailTabs/index.jsx
src/components/EnhanceTable/index.jsx
src/pages/Dashboard/Clusters/columns/index.js
src/pages/Dashboard/Clusters/index.jsx
src/pages/Dashboard/Clusters/index.scss
src/pages/Dashboard/Runtimes/Detail/index.jsx
src/pages/Dashboard/Runtimes/InstanceList/index.jsx
src/pages/Dashboard/UserInstance/index.jsx
src/pages/Dashboard/UserSandbox/index.jsx
src/pages/Dashboard/index.js
src/routes/portals/dev.jsx
src/stores/cluster/index.js
src/stores/runtime/cluster.js
src/stores/runtime/index.js

Fix Enhance table column check

refactor: Cluster list page add frontgate tab

---

src/pages/Dashboard/Runtimes/InstanceList/columns.js
src/stores/runtime/cluster.js

fix: Runtime detail page of cluster's configuration column

---

src/pages/Dashboard/Runtimes/Detail/index.jsx

fix: Runtime tab of K8s

---

src/components/Base/Icon/index.scss
src/pages/Dashboard/CloudEnv/index.jsx
src/pages/Dashboard/CloudEnv/index.scss
src/pages/Dashboard/Runtimes/index.jsx
src/scss/partial/_icon.scss

style: Platform icon color

---

.prettierrc
lib/config-parser/vm.js
src/locales/zh/base.json
src/pages/Dashboard/Clusters/Detail/Helm/index.jsx
src/pages/Dashboard/Clusters/Detail/VMbase/index.jsx
src/pages/Dashboard/Clusters/Detail/index.jsx
src/stores/cluster/detail.js
src/stores/cluster/index.js
src/utils/object.js

refine VM and Helm type update env

refactor: VM based cluster update env

---

src/pages/Dashboard/Account/index.jsx
src/pages/Dashboard/Apps/Audits/index.jsx
src/pages/Dashboard/Apps/Detail/index.jsx
src/pages/Dashboard/Reviews/Detail/index.jsx
src/pages/Dashboard/Versions/Detail/index.jsx
src/routes/portals/dev.jsx
src/stores/app/version.js

chore: App detail page version audits add pagination

---

src/components/Layout/SideNav/navMap.js
src/pages/Dashboard/Apps/Deploy/index.jsx
src/pages/Dashboard/Apps/Info/index.jsx
src/pages/Dashboard/Reviews/Detail/index.jsx
src/providers/user.js
src/stores/cluster/index.js

* fix: Admin portal agent query used debug_clusters
Solved #1021, #1022, #1023

fix: Deploy skip link

---

src/components/Base/Checkbox/checkbox.jsx
src/components/Base/Checkbox/index.scss

fix: Table checkbox

---

src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/navMap.js
src/config/action-id.js
src/stores/user/role.js

refactor: Hide nav for app review

---

src/pages/Dashboard/Account/index.jsx

fix: Account page handle save

---

src/components/Banner/index.scss
src/components/Base/Modal/index.scss
src/pages/Home/index.jsx
src/stores/RootStore.js

Refactor home page scroll animation speed

fix: Category page modal height

---

src/portals/admin/pages/Users/Modals/index.jsx
src/portals/admin/pages/Users/columns.js
src/portals/admin/pages/Users/index.jsx
src/stores/user/group.js

refactor: Admin user page hide some actions for non-admin user

---

src/components/DetailTabs/index.scss
src/components/Layout/SideNav/index.jsx
src/components/TdName/index.scss
src/config/form-check.js
src/locales/en/base.json
src/locales/zh/apps.json
src/locales/zh/deploy.json
src/pages/Dashboard/Account/SSHKeys/index.jsx
src/pages/Dashboard/Apps/Deploy/index.jsx
src/pages/Dashboard/Apps/Detail/index.jsx
src/pages/Dashboard/Clusters/columns/index.js
src/pages/Dashboard/Clusters/index.jsx
src/pages/Dashboard/Clusters/index.scss
src/pages/Dashboard/Reviews/Detail/index.jsx
src/pages/Dashboard/Reviews/index.jsx
src/pages/Dashboard/UserInstance/index.jsx
src/pages/Dashboard/UserSandbox/index.jsx
src/pages/Dashboard/Versions/Detail/index.jsx
src/stores/app/index.js
src/stores/app/version.js
src/stores/cluster/index.js

* fix: Version NO check support default value
* fix: ISV review add deploy button
* fix: SSH key attch key error
* fix: Clusters page reset defalut status
* fix: Reviews page pagination query error
* fix: Local menu apps refresh with api response data 
* fix: Nav menu logo skip link to self portal
* fix: Version sumbit review refresh latest record 
* fix: Sandbox instancespage add agent tab 
* fix: Remove reveiw detail page standard link

fix: App version and review related issues

---

src/locales/zh/category.json
src/pages/Dashboard/Categories/index.jsx
src/pages/Dashboard/Categories/index.scss
src/stores/app/uncategoried.js
src/stores/category/index.js

Add app to cate, can not choose app
Refactor hide create btn when category reserved

fix: Category page issues

---

src/components/Deploy/section.jsx
src/locales/zh/deploy.json
src/pages/Dashboard/Apps/Deploy/index.jsx

fix: Add regex for helm appName

---

src/components/MenuLayer/index.scss
src/pages/Dashboard/Account/SSHKeys/index.jsx
src/pages/Dashboard/Account/SSHKeys/index.scss
src/pages/Dashboard/Clusters/columns/index.js
src/pages/Dashboard/Clusters/index.jsx
src/pages/Dashboard/Clusters/index.scss
src/pages/Dashboard/Runtimes/Card/index.jsx
src/pages/Dashboard/Runtimes/Detail/index.jsx
src/pages/Dashboard/Runtimes/index.scss
src/portals/user/pages/PurchasedApps/Detail/index.jsx

* fix: MenuLayer icon style and SSH keys style

fix: Runtime detail reference clusters page

---

src/mixins/setPage.js
src/mixins/tableActions.js
src/pages/Dashboard/Apps/Info/index.jsx
src/pages/Dashboard/Providers/Applications/index.jsx
src/pages/Dashboard/Providers/index.jsx
src/pages/Dashboard/Reviews/Detail/index.jsx
src/pages/Dashboard/Reviews/index.jsx
src/stores/app/version.js
src/stores/vendor/index.js

* fix: Hide terms of service about app info
fixed #1059

fix: Remember the active type in table

---

src/pages/Dashboard/Apps/Add/index.jsx
src/pages/Dashboard/Categories/index.jsx
src/stores/Store.js
src/stores/app/create.js
src/stores/app/deploy.js
src/stores/app/index.js
src/stores/app/uncategoried.js
src/stores/app/version.js
src/stores/category/index.js
src/stores/cloud_env/index.js
src/stores/cluster/detail.js
src/stores/cluster/index.js
src/stores/key_pair/index.js
src/stores/notification_server/index.js
src/stores/repo/create.js
src/stores/repo/index.js
src/stores/runtime/cluster.js
src/stores/runtime/credential.js
src/stores/runtime/index.js
src/stores/testing_env/create.js
src/stores/testing_env/index.js
src/stores/user/detail.js
src/stores/user/group.js
src/stores/user/index.js
src/stores/user/role.js
src/stores/vendor/index.js

refactor: New way to define observables in store class, auto handle store reset

---

src/App.jsx
src/components/Base/Switch/index.scss
src/components/Base/Tree/index.scss
src/components/Can/enhanced.jsx
src/components/Can/index.js
src/components/Can/index.jsx
src/components/Collapse/index.scss
src/components/Layout/SideNav/index.jsx
src/components/Layout/SideNav/navMap.js
src/components/MenuLayer/index.jsx
src/components/Toolbar/index.jsx
src/config/action-id.js
src/config/roles.js
src/pages/Dashboard/Account/index.jsx
src/portals/admin/pages/Roles/Popover/index.jsx
src/portals/admin/pages/Roles/RoleTree/index.jsx
src/portals/admin/pages/Users/index.jsx
src/portals/admin/pages/Users/index.scss
src/stores/app/version.js
src/stores/user/index.js
src/stores/user/role.js
src/utils/checkAction.js
src/utils/index.js

chore: Set navigation menu according to permissions

---

server/routes/page.js
src/components/Base/Image/index.jsx
src/components/Base/Notification/item.jsx
src/components/Base/PopoverIcon/index.scss
src/components/Base/Table/index.scss
src/components/DetailTabs/index.scss
src/components/EnhanceTable/columns.js
src/components/Layout/SideNav/index.scss
src/components/TdName/index.scss
src/pages/AppDetail/index.jsx
src/pages/Dashboard/Account/SSHKeys/index.scss
src/pages/Dashboard/Apps/AppInfo/index.jsx
src/pages/Dashboard/Apps/Audits/index.jsx
src/pages/Dashboard/Apps/Detail/index.jsx
src/pages/Dashboard/Apps/Info/index.jsx
src/pages/Dashboard/Apps/index.jsx
src/pages/Dashboard/Categories/index.jsx
src/pages/Dashboard/Clusters/index.jsx
src/pages/Dashboard/Clusters/index.scss
src/pages/Dashboard/Providers/Applications/Detail/index.jsx
src/pages/Dashboard/Providers/Detail/index.jsx
src/pages/Dashboard/Reviews/Detail/index.jsx
src/pages/Dashboard/Versions/Detail/index.jsx
src/pages/Dashboard/Versions/index.jsx
src/portals/user/Layout/index.jsx
src/portals/user/pages/PurchasedApps/index.jsx
src/providers/user.js
src/stores/app/index.js
src/stores/app/version.js
src/stores/cluster/index.js

*  refactor: Apps deploy statistics total query
* fix: Query menu apps only once after login

chore: Detail pages add loading style

---

jest.config.json
server/render-page.js

Render page bottom js no need defer

refactor: Jest config not show coverage files

---

package.json
src/App.jsx
src/components/MenuLayer/index.scss
src/pages/Dashboard/Clusters/index.jsx
src/routes/index.js
src/routes/portals/index.js
yarn.lock

Remove babel-core due to jest v24

fix: Cyclic dependency in routes module

---

lib/request.js
src/components/Base/Notification/item.jsx
src/providers/sock-client.js

Notification timeout as 10s, hide when click

chore: Format request error message
